general:
  name: "Edita"
  summary: "Elevate your text writing"
  description: "Edita brings you a simple dialog to beautify text from Textfields in Android"
  url: "https://edita.robingebert.com"
  #logo_icon: lucide-lab:chest
  logo_image: "/src/site/img/logo.png"
  color: 
    light: "#FF5722"
    dark: "#E64A19"
  version: "1.0.0"
  device: "smartphone" # "smartphone" | "desktop" | "browser"

store:
  play_store: "https://play.google.com/store/apps/details?id=com.ronjar.edita"

features:
  - title: "Easy usage"
    description: "Just mark the text end click on Edita, select your options and click on Paste"
    icon: "material-symbols:text-select-move-forward-character"

  - title: "Rich options"
    description: Edita offers bold, italic, but also fracture, monospace and various combinations of it."
    icon: "material-symbols:format-color-text"
    link: "sites/Options"

  - title: "No tracking etc."
    description: "I don't collect any data, tracking whatsoever."
    icon: "material-symbols:bar-chart-off"
    link: "sites/PrivacyPolicy"