general:
  name: "Casey"
  summary: "A showcasing CMS written in Svelte"
  description: "Casey is a CMS that is written in Svelte and showcases the power of Svelte."
  url: "https://example.com"
  logo_icon: lucide-lab:chest
  color: 
    light: "#FF5722"
    dark: "#E64A19"
  version: "1.0.0"
  device: "desktop" # "smartphone" | "desktop" | "browser"

store:
  play_store: "https://play.google.com/store/apps/details?id=com.example"
  app_store: "https://apps.apple.com/us/app/example/id1234567890"
  microsoft_store: "https://www.microsoft.com/store/apps/9NBLGGH4R315"

features:
  - title: "Easy configuration"
    description: "Configure it using just 2 YAML files and markdown for additional sites."
    icon: "material-symbols:edit-square-outline-rounded"
    link: "/feature-easy-configuration"

  - title: "Responsive layout"
    description: "Casey is responsive and works on all devices and browsers."
    icon: "material-symbols:devices-outline-rounded"
    link: "/feature-responsive-layout"

  - title: "Static deployment"
    description: "Deploy your site as a static site using Vercel, Netlify, or GitHub Pages."
    icon: "material-symbols:rocket-launch-rounded"
    link: "https://robingebert.com"