name: "ExampleCompany"
slogan: "Example slogan" # Tet below the name
logo_icon: "material-symbols:domain-rounded"
#logo_img: "/images/logo.svg" # Use either logo_icon or logo_img
footer:
  title: "Company Links"
  menu:
    - title: "Jobs"
      link: "https://jobs.example.com"
    - title: "About"
      link: "https://about.example.com"
