name: "Ronjar"
slogan: "© 2025" # Tet below the name
logo_icon: "material-symbols:domain-rounded"
#logo_img: "/images/logo.svg" # Use either logo_icon or logo_img
footer:
  title: "About me"
  menu:
    - title: "Personal site"
      link: "https://robingebert.com"
    - title: "Github"
      link: "https://github.com/ronjar"
